// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.

// Generated by Quartus II Version 13.0.1 Build 232 06/12/2013 Service Pack 1 SJ Web Edition
// Created on Mon Mar 11 10:39:46 2024

// synthesis message_off 10175

`timescale 1ns/1ns

module maquina_estados (
    reset,clock,
    output1,output2,output3);

    input reset;
    input clock;
    tri0 reset;
    output output1;
    output output2;
    output output3;
    reg output1;
    reg output2;
    reg output3;
    reg [7:0] fstate;
    reg [7:0] reg_fstate;
    parameter state6=0,state4=1,state2=2,state3=3,state5=4,state8=5,state7=6,state1=7;

    always @(posedge clock)
    begin
        if (clock) begin
            fstate <= reg_fstate;
        end
    end

    always @(fstate or reset)
    begin
        if (reset) begin
            reg_fstate <= state1;
            output1 <= 1'b0;
            output2 <= 1'b0;
            output3 <= 1'b0;
        end
        else begin
            output1 <= 1'b0;
            output2 <= 1'b0;
            output3 <= 1'b0;
            case (fstate)
                state6: begin
                    reg_fstate <= state7;

                    output2 <= 1'b0;

                    output3 <= 1'b1;

                    output1 <= 1'b1;
                end
                state4: begin
                    reg_fstate <= state5;

                    output2 <= 1'b1;

                    output3 <= 1'b1;

                    output1 <= 1'b0;
                end
                state2: begin
                    reg_fstate <= state3;

                    output2 <= 1'b0;

                    output3 <= 1'b1;

                    output1 <= 1'b0;
                end
                state3: begin
                    reg_fstate <= state4;

                    output2 <= 1'b1;

                    output3 <= 1'b0;

                    output1 <= 1'b0;
                end
                state5: begin
                    reg_fstate <= state6;

                    output2 <= 1'b0;

                    output3 <= 1'b0;

                    output1 <= 1'b1;
                end
                state8: begin
                    reg_fstate <= state1;

                    output2 <= 1'b1;

                    output3 <= 1'b1;

                    output1 <= 1'b1;
                end
                state7: begin
                    reg_fstate <= state8;

                    output2 <= 1'b1;

                    output3 <= 1'b0;

                    output1 <= 1'b1;
                end
                state1: begin
                    reg_fstate <= state2;

                    output2 <= 1'b0;

                    output3 <= 1'b0;

                    output1 <= 1'b0;
                end
                default: begin
                    output1 <= 1'bx;
                    output2 <= 1'bx;
                    output3 <= 1'bx;
                    $display ("Reach undefined state");
                end
            endcase
        end
    end
endmodule // maquina_estados
